# Generated by Django 4.0.5 on 2022-06-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_tempo_prepato_receita_tempo_preparo'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
